-- INSERTs for Visitor_Interested_Event
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (36, 1, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (56, 1, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (17, 1, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (48, 2, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (13, 2, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 2, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (55, 3, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (62, 3, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (60, 3, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 4, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (45, 5, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 5, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 6, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (44, 6, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (15, 7, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 7, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 8, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 8, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (23, 9, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (62, 9, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 10, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (23, 10, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (13, 10, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (9, 11, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (23, 11, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (54, 11, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (30, 12, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 12, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (22, 13, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (32, 14, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (63, 14, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (46, 14, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 15, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 16, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (43, 17, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (37, 18, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 19, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (64, 20, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (66, 20, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 20, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (5, 21, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (47, 21, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (22, 21, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (80, 22, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 22, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 23, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (46, 23, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (33, 23, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (53, 24, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (18, 24, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 24, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (28, 25, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (70, 25, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (37, 25, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 26, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (47, 26, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (22, 27, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (39, 28, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (32, 29, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 29, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 30, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (1, 31, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (36, 32, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (49, 33, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (56, 33, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 34, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (17, 35, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (59, 35, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (28, 36, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 37, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (17, 38, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (61, 38, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (30, 38, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (13, 39, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (9, 40, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (2, 40, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (16, 41, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 41, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (19, 42, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (29, 42, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (56, 42, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (22, 43, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (62, 43, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 44, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (44, 45, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (66, 45, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 45, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (56, 46, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 46, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 47, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (75, 48, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 48, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (25, 48, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (22, 49, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 49, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (2, 50, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (78, 50, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 51, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 52, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (67, 52, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (1, 52, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (7, 53, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 54, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (47, 54, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 55, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (80, 55, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (32, 56, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (62, 57, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (63, 58, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 59, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (77, 59, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (37, 60, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (7, 61, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (51, 61, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (4, 62, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (8, 62, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (16, 63, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 63, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (73, 63, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (18, 64, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 65, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 65, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (48, 66, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (10, 67, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (53, 67, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (73, 67, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (46, 68, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (14, 69, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (54, 69, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (58, 69, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (40, 70, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (73, 71, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (77, 71, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (42, 72, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (28, 72, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (64, 72, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 73, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (40, 74, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (3, 74, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (25, 75, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (30, 76, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 76, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 77, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (51, 77, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (48, 77, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 78, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (60, 79, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (75, 79, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (80, 80, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (43, 80, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (20, 80, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 81, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 81, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (49, 81, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 82, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (76, 82, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (78, 82, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (64, 83, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 83, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 84, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (58, 85, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (10, 85, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (69, 85, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 86, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (14, 87, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (80, 88, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (43, 89, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 89, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (9, 90, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 91, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 92, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 93, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 94, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (43, 95, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (37, 96, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (33, 97, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (28, 97, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 98, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (78, 99, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (3, 99, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 100, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (42, 101, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 101, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (2, 101, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (7, 102, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (70, 103, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 103, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (58, 103, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (74, 104, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (25, 104, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (30, 104, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (22, 105, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (2, 105, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (47, 106, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (19, 107, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (37, 107, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 107, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (39, 108, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (60, 108, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 109, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (10, 109, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 109, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (15, 110, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (26, 111, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (55, 112, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (3, 112, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (73, 113, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (19, 113, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 113, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 114, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 114, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (24, 114, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (3, 115, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 115, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 116, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (9, 116, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (73, 117, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (18, 117, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (32, 117, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (49, 118, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (33, 118, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (76, 119, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (5, 119, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (58, 120, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 120, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (19, 121, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (71, 122, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 122, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (16, 123, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (69, 123, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (26, 123, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (50, 124, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (30, 125, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (20, 125, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (40, 125, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 126, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (67, 126, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (55, 127, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (75, 127, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (45, 127, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (48, 128, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (9, 128, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (39, 129, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (49, 130, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 131, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (21, 131, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 131, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (17, 132, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (29, 133, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (55, 133, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (21, 134, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (71, 134, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (61, 134, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 135, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 135, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (24, 135, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 136, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 136, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (47, 137, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (28, 137, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (4, 138, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 139, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (16, 140, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (40, 140, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 141, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (46, 141, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (60, 142, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (21, 143, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (44, 143, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 143, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (10, 144, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (36, 144, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (36, 145, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 145, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (55, 145, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (28, 146, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 146, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (66, 147, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (62, 147, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (51, 147, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (18, 148, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 148, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (46, 148, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 149, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (39, 149, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (5, 150, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 150, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (7, 151, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (4, 152, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 152, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 153, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (77, 153, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (45, 154, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (78, 154, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (67, 155, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (68, 155, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 156, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (29, 157, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (71, 157, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 157, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (49, 158, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (24, 159, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (61, 159, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (47, 160, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (10, 160, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 160, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (14, 161, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (55, 161, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 161, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (18, 162, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (36, 162, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 162, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (10, 163, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 163, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 164, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (59, 164, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 164, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (52, 165, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (2, 165, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (24, 165, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (76, 166, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (3, 166, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (59, 166, 'VIP', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 167, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 167, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (35, 168, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (27, 168, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (77, 168, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (9, 169, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (15, 169, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (39, 169, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (36, 170, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (6, 170, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (67, 171, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (75, 172, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 172, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (16, 172, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (4, 173, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (73, 173, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (5, 173, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (21, 174, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (24, 174, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (18, 174, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 175, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (58, 175, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (39, 176, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (2, 177, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (71, 177, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (42, 178, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (7, 178, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (20, 179, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (17, 179, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (51, 180, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (14, 180, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (40, 180, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (51, 181, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (17, 181, 'Student', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (33, 182, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 183, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (38, 183, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (29, 184, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (60, 184, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (66, 185, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 186, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 186, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 186, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (64, 187, 'Standard', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (48, 187, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (60, 187, 'Backstage', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (34, 188, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (79, 188, 'Backstage', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (14, 189, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (12, 189, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (62, 190, 'Student', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (51, 190, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 190, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (57, 191, 'Standard', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (41, 191, 'Standard', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (44, 192, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (58, 193, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (31, 193, 'Backstage', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (32, 193, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (21, 194, 'Backstage', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (72, 194, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (71, 195, 'VIP', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (74, 196, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (40, 196, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (56, 196, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (4, 197, 'Student', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (65, 197, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (11, 197, 'Student', 'Bank Transfer');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (59, 198, 'VIP', 'Credit Card');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (19, 199, 'Standard', 'Cash');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (7, 200, 'VIP', 'PayPal');
INSERT INTO Visitor_Interested_Event (Event_ID, Visitor_ID, Type_ID, Payment_ID) VALUES (61, 200, 'Standard', 'Cash');
