-- Generated INSERTs for Genre table
INSERT INTO Genre (ID, Name) VALUES (1, 'Rock');
INSERT INTO Genre (ID, Name) VALUES (2, 'Jazz');
INSERT INTO Genre (ID, Name) VALUES (3, 'Classical');
INSERT INTO Genre (ID, Name) VALUES (4, 'Hip Hop');
INSERT INTO Genre (ID, Name) VALUES (5, 'Electronic');
INSERT INTO Genre (ID, Name) VALUES (6, 'Pop');
INSERT INTO Genre (ID, Name) VALUES (7, 'Folk');
INSERT INTO Genre (ID, Name) VALUES (8, 'Blues');
INSERT INTO Genre (ID, Name) VALUES (9, 'Reggae');
INSERT INTO Genre (ID, Name) VALUES (10, 'Metal');
INSERT INTO Genre (ID, Name) VALUES (11, 'Punk');
INSERT INTO Genre (ID, Name) VALUES (12, 'Country');
INSERT INTO Genre (ID, Name) VALUES (13, 'Soul');
INSERT INTO Genre (ID, Name) VALUES (14, 'Funk');
INSERT INTO Genre (ID, Name) VALUES (15, 'Techno');
INSERT INTO Genre (ID, Name) VALUES (16, 'Opera');
INSERT INTO Genre (ID, Name) VALUES (17, 'R&B');
INSERT INTO Genre (ID, Name) VALUES (18, 'Indie');
INSERT INTO Genre (ID, Name) VALUES (19, 'House');
INSERT INTO Genre (ID, Name) VALUES (20, 'Trance');
