-- Generated INSERTs for Performer table
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (1, 'Kristen Hull', 'Man Artist', '1970-10-31', 'brian01', 'https://anderson.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (2, 'Victoria Adkins', 'Reduce Artist', '1970-02-15', 'drivas', 'https://www.johnson.biz/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (3, NULL, 'Church Band', NULL, 'taylorbrittany', 'http://rodriguez.com/', 1, '2005-06-10');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (4, 'Donald Hooper', 'Century Artist', '2003-06-25', 'morganscott', 'http://burns.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (5, NULL, 'Particular Band', NULL, 'fjoseph', 'http://murphy.com/', 1, '1999-04-02');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (6, NULL, 'Play Band', NULL, 'hlawson', 'https://sanchez.com/', 1, '2005-10-11');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (7, NULL, 'Way Band', NULL, 'iyork', 'http://jones.biz/', 1, '2013-08-21');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (8, NULL, 'Another Band', NULL, 'justinrios', 'https://cain-white.com/', 1, '2011-12-07');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (9, 'Rachel Smith', 'Federal Artist', '1989-09-10', 'gknight', 'https://douglas.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (10, 'Eric Williams', 'Sea Artist', '2004-06-20', 'qvincent', 'https://www.anderson.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (11, NULL, 'Shake Band', NULL, 'carrillodustin', 'https://young.com/', 1, '2014-02-04');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (12, NULL, 'Board Band', NULL, 'reedstephanie', 'https://herrera.com/', 1, '1998-01-13');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (13, NULL, 'Up Band', NULL, 'rodneymeyer', 'http://www.rice.com/', 1, '2006-12-18');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (14, NULL, 'Wear Band', NULL, 'zbarrera', 'http://edwards-hooper.net/', 1, '2003-05-31');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (15, 'Kevin Irwin', 'Future Artist', '1965-05-15', 'leechristopher', 'http://www.villa.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (16, 'Shannon Calderon', 'Section Artist', '2004-04-01', 'ephelps', 'http://www.murphy-li.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (17, NULL, 'Explain Band', NULL, 'theresalopez', 'http://www.barnes.info/', 1, '2010-08-19');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (18, 'Kara Jordan', 'Type Artist', '1985-07-24', 'simpsondavid', 'http://www.nelson.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (19, NULL, 'They Band', NULL, 'sharonhoward', 'http://cabrera-gregory.net/', 1, '1998-07-05');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (20, 'John Barnett', 'Population Artist', '1964-08-11', 'aaron45', 'http://www.johnson.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (21, 'Stephanie Romero', 'Set Artist', '1978-01-02', 'lauragillespie', 'https://www.harrell.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (22, NULL, 'Always Band', NULL, 'kimberly29', 'http://coleman-phillips.org/', 1, '2010-12-23');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (23, NULL, 'Cup Band', NULL, 'julie68', 'http://stone-harvey.com/', 1, '2017-12-24');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (24, NULL, 'Theory Band', NULL, 'andersonapril', 'http://aguilar.com/', 1, '2023-12-11');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (25, NULL, 'Enjoy Band', NULL, 'ashleysingh', 'https://ramirez.biz/', 1, '2007-10-19');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (26, NULL, 'Large Band', NULL, 'brucelaura', 'https://stout.net/', 1, '2011-03-05');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (27, 'Pamela Smith', 'Even Artist', '1975-05-19', 'ckennedy', 'https://howard-stout.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (28, NULL, 'Age Band', NULL, 'nicole55', 'https://www.taylor.com/', 1, '2019-04-28');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (29, 'John Ryan', 'Main Artist', '1969-09-19', 'maryspears', 'http://johnson.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (30, NULL, 'Friend Band', NULL, 'annette50', 'http://austin-phelps.com/', 1, '2013-11-30');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (31, NULL, 'Growth Band', NULL, 'tsmith', 'http://www.freeman-hebert.com/', 1, '2001-04-03');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (32, NULL, 'Specific Band', NULL, 'dawsoncorey', 'http://www.wilcox.com/', 1, '2020-06-11');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (33, NULL, 'Parent Band', NULL, 'froach', 'http://hernandez.com/', 1, '2013-04-21');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (34, 'Michaela Watts', 'Turn Artist', '1996-05-21', 'udrake', 'https://williams.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (35, NULL, 'Account Band', NULL, 'tina30', 'https://rhodes-navarro.com/', 1, '2018-08-20');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (36, NULL, 'Themselves Band', NULL, 'tinabailey', 'http://www.bell-mcguire.com/', 1, '2021-07-29');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (37, NULL, 'Trade Band', NULL, 'gregory36', 'https://burnett-murray.com/', 1, '2011-10-04');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (38, 'Anita Newton', 'Believe Artist', '1983-01-05', 'maryallen', 'http://www.kennedy.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (39, NULL, 'Decade Band', NULL, 'reginald40', 'https://www.johnson.com/', 1, '2020-01-25');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (40, 'Daniel Smith', 'East Artist', '1985-01-18', 'bduncan', 'http://alvarez-elliott.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (41, NULL, 'Together Band', NULL, 'ecampbell', 'https://perez.com/', 1, '2002-12-13');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (42, 'Tiffany Ball', 'Although Artist', '1982-07-30', 'mackenzie34', 'http://www.matthews-jones.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (43, NULL, 'Entire Band', NULL, 'wendytodd', 'http://www.phillips.com/', 1, '2021-10-16');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (44, NULL, 'Fish Band', NULL, 'laurasmith', 'https://www.oneal-barry.org/', 1, '2023-07-05');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (45, 'Megan Newman DVM', 'Left Artist', '1996-11-01', 'joshua41', 'https://www.martinez.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (46, NULL, 'Just Band', NULL, 'ghunter', 'https://www.garcia-love.com/', 1, '2010-03-20');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (47, 'Elizabeth Munoz', 'Others Artist', '1980-03-23', 'daniel96', 'http://www.buckley.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (48, 'Robert Petersen', 'Factor Artist', '1981-04-24', 'kgill', 'https://smith.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (49, NULL, 'Hot Band', NULL, 'jeffreyduffy', 'https://www.johns-fields.org/', 1, '1999-05-17');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (50, 'Jordan Gilmore', 'Church Artist', '1969-11-05', 'whitesean', 'https://terry.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (51, NULL, 'Food Band', NULL, 'ginahill', 'http://www.mccann-nichols.com/', 1, '2012-03-03');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (52, NULL, 'Someone Band', NULL, 'sydney71', 'https://www.herrera.biz/', 1, '2002-11-24');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (53, NULL, 'Former Band', NULL, 'emily36', 'https://roy.com/', 1, '2017-09-29');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (54, 'Justin Alexander', 'And Artist', '1993-04-23', 'suttonemily', 'http://richardson.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (55, NULL, 'Relate Band', NULL, 'david89', 'https://may-flowers.com/', 1, '2010-03-03');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (56, 'William Nichols', 'Avoid Artist', '1972-03-12', 'tayloramanda', 'https://le-gilbert.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (57, 'Corey Smith', 'Prevent Artist', '1977-08-28', 'garciapamela', 'https://www.thornton-hickman.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (58, NULL, 'Collection Band', NULL, 'sweeneyjackie', 'https://www.sheppard-rice.info/', 1, '2013-07-17');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (59, 'Emily Harper', 'Choose Artist', '1990-03-23', 'rmurphy', 'http://turner.biz/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (60, NULL, 'Thousand Band', NULL, 'amoran', 'http://www.valdez.com/', 1, '2021-11-04');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (61, 'Sara Aguilar', 'Question Artist', '1998-07-09', 'rachel50', 'http://donovan-mullen.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (62, 'Robert Alvarez', 'Oil Artist', '1990-08-12', 'jwilliamson', 'http://thomas-burke.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (63, 'Arthur Swanson', 'Model Artist', '2001-07-18', 'debbieedwards', 'https://wright.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (64, NULL, 'Player Band', NULL, 'zbrown', 'http://garcia.com/', 1, '2016-10-06');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (65, 'Scott Kent', 'When Artist', '1987-01-08', 'evelyndalton', 'http://www.elliott.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (66, 'Mary Cobb', 'No Artist', '1982-01-01', 'tina88', 'http://klein.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (67, 'John York', 'Issue Artist', '1986-12-23', 'ryan45', 'https://garrett.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (68, NULL, 'Support Band', NULL, 'denise94', 'http://houston-frank.com/', 1, '1996-06-08');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (69, 'Casey Johnson', 'Few Artist', '1984-08-26', 'rose95', 'https://www.cardenas.biz/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (70, 'Dalton Thompson', 'Wind Artist', '1984-03-28', 'nhoward', 'https://www.kent-rivera.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (71, NULL, 'Hotel Band', NULL, 'icampos', 'http://www.rodriguez.net/', 1, '2008-04-25');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (72, 'Jorge Fox', 'Statement Artist', '1968-04-07', 'matthewmoon', 'https://white.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (73, 'Julia Johnson', 'Quality Artist', '1966-08-01', 'normamurphy', 'https://www.lee.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (74, 'Susan Montes', 'Suddenly Artist', '1969-07-17', 'gary34', 'https://www.carter.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (75, NULL, 'Per Band', NULL, 'nelsonjacob', 'http://www.burch-best.biz/', 1, '2022-09-26');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (76, 'Richard Carr', 'System Artist', '1995-06-06', 'sotojanet', 'http://www.campbell-smith.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (77, NULL, 'Memory Band', NULL, 'tdaniels', 'https://www.bernard-figueroa.org/', 1, '2010-09-01');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (78, 'Tiffany Harper', 'Rather Artist', '2004-06-18', 'beltranmichael', 'https://parrish-fitzgerald.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (79, NULL, 'Strong Band', NULL, 'hugheswalter', 'https://hammond.com/', 1, '2008-07-21');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (80, NULL, 'Station Band', NULL, 'smithmichael', 'https://www.francis.org/', 1, '2006-07-25');

-- Generated INSERTs for Membership table
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (6, 1, '2020-02-25');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (52, 2, '2021-01-10');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (79, 9, '2016-05-08');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (77, 10, '2019-10-24');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (80, 15, '2023-01-06');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (22, 21, '2017-07-25');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (31, 38, '2021-09-18');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (79, 40, '2017-03-19');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (39, 42, '2017-07-21');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (75, 48, '2016-11-15');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (80, 50, '2017-11-01');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (58, 54, '2021-09-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (58, 56, '2017-10-16');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (32, 57, '2017-10-03');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (68, 61, '2016-01-24');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (44, 62, '2015-12-18');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (58, 66, '2021-06-07');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (64, 67, '2018-04-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (23, 69, '2023-11-30');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (17, 73, '2023-10-06');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (52, 78, '2018-11-21');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (3, 1, '2024-10-13');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (5, 2, '2025-04-09');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (6, 4, '2022-09-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (7, 9, '2025-04-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (8, 10, '2018-05-12');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (11, 15, '2015-09-22');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (12, 16, '2019-02-06');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (13, 18, '2017-01-03');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (14, 20, '2017-08-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (17, 21, '2023-04-12');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (19, 27, '2018-01-10');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (22, 29, '2024-10-11');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (23, 34, '2016-08-09');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (24, 38, '2017-12-30');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (25, 40, '2015-07-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (26, 42, '2019-10-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (28, 45, '2018-08-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (30, 47, '2015-06-30');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (31, 48, '2017-08-18');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (32, 50, '2020-12-08');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (33, 54, '2017-01-03');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (35, 56, '2016-12-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (36, 57, '2024-11-11');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (37, 59, '2024-01-15');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (39, 61, '2016-04-01');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (41, 62, '2019-09-27');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (43, 63, '2021-06-21');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (44, 65, '2019-07-01');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (46, 66, '2024-11-25');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (49, 67, '2019-12-18');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (51, 69, '2022-05-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (53, 70, '2021-01-03');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (55, 72, '2020-04-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (60, 73, '2025-04-16');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (64, 74, '2023-03-04');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (68, 76, '2022-08-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (71, 78, '2021-05-20');
