-- Generated INSERTs for Performer table
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (1, NULL, 'Become Band', NULL, 'fmitchell', 'http://www.griffith.com/', 1, '2008-07-21');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (2, 'Lauren Sanders', 'Large Artist', '1986-06-16', 'josephhess', 'https://www.bell.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (3, 'Kelly Johnson', 'Decide Artist', '1989-12-16', 'ryanbrennan', 'http://jackson.biz/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (4, 'Nancy Kelley', 'Life Artist', '1969-08-02', 'uharris', 'https://hodge.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (5, 'Christopher Smith', 'Summer Artist', '1967-07-25', 'wcohen', 'http://www.dyer.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (6, NULL, 'Perform Band', NULL, 'wilsonsabrina', 'https://www.russell.com/', 1, '2012-11-14');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (7, NULL, 'Something Band', NULL, 'mariahlane', 'https://www.nunez-may.com/', 1, '2002-02-28');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (8, NULL, 'According Band', NULL, 'gkelly', 'https://gonzalez.com/', 1, '1998-06-10');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (9, NULL, 'Image Band', NULL, 'kimberly27', 'http://stephens-moore.com/', 1, '2018-12-06');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (10, NULL, 'Despite Band', NULL, 'latoyawells', 'https://young.com/', 1, '2010-03-08');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (11, 'David Moore', 'Store Artist', '1990-09-27', 'caleb66', 'https://www.yates-kirby.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (12, 'Debra Price', 'Early Artist', '1966-04-19', 'todd44', 'http://www.harrison.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (13, 'Joanne Coleman', 'Budget Artist', '1991-01-29', 'tcruz', 'https://www.bradford.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (14, NULL, 'At Band', NULL, 'heather41', 'https://www.bailey.com/', 1, '1996-10-28');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (15, 'Samantha Allen PhD', 'Director Artist', '1973-02-21', 'emilycortez', 'http://www.orozco-morgan.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (16, 'Tracey West', 'Ready Artist', '1994-04-07', 'npearson', 'https://davis.biz/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (17, 'Emily Montgomery', 'Third Artist', '1972-08-26', 'fitzgeraldmitchell', 'https://www.stewart.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (18, NULL, 'Option Band', NULL, 'svillarreal', 'https://rodriguez.com/', 1, '2002-03-15');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (19, 'Diana Jackson', 'Yeah Artist', '2002-10-11', 'callen', 'http://www.griffin.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (20, 'David Rosales', 'Mention Artist', '1988-03-03', 'tonya40', 'https://www.campbell.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (21, 'Alex Brown', 'Camera Artist', '1973-12-31', 'richardskristen', 'http://www.may.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (22, 'Mr. Justin Gilbert', 'Image Artist', '1990-07-31', 'jeremy41', 'https://www.cook.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (23, NULL, 'Happen Band', NULL, 'wellsanna', 'https://mayer.biz/', 1, '2007-11-27');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (24, NULL, 'Suffer Band', NULL, 'gary38', 'http://simpson.info/', 1, '1997-05-10');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (25, NULL, 'Standard Band', NULL, 'qedwards', 'http://www.williams-tyler.info/', 1, '2007-02-25');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (26, 'Lisa Cole', 'Deep Artist', '1974-09-08', 'charles82', 'https://www.castillo.biz/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (27, NULL, 'Indeed Band', NULL, 'iblack', 'http://cook.com/', 1, '2017-08-04');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (28, 'Kristina Huff', 'College Artist', '1972-09-12', 'joshua48', 'http://www.taylor.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (29, NULL, 'Pm Band', NULL, 'zkennedy', 'http://hernandez-herrera.info/', 1, '2021-11-11');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (30, 'Samantha Jones DDS', 'More Artist', '1980-06-12', 'htaylor', 'http://pruitt-reid.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (31, NULL, 'To Band', NULL, 'cisneroslinda', 'https://smith.com/', 1, '2019-02-20');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (32, 'Jacqueline Rogers', 'Evidence Artist', '2002-09-10', 'smithdonna', 'https://taylor.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (33, NULL, 'Firm Band', NULL, 'nwhitney', 'https://www.johnson-meyer.com/', 1, '2006-04-03');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (34, 'Donna Aguilar', 'Never Artist', '1974-02-17', 'chad43', 'http://taylor.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (35, NULL, 'Moment Band', NULL, 'lucas02', 'https://www.davis-johnson.org/', 1, '2008-08-16');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (36, 'Heidi Le', 'School Artist', '1983-06-30', 'darrell54', 'http://www.lyons-gordon.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (37, NULL, 'Field Band', NULL, 'watsonjeffrey', 'http://www.mcmillan.biz/', 1, '2010-11-28');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (38, 'Diana Jackson', 'Wind Artist', '1971-04-13', 'simpsonsarah', 'http://smith-brown.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (39, NULL, 'Morning Band', NULL, 'fbanks', 'https://www.morris.com/', 1, '2016-07-15');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (40, 'Wanda Snyder', 'Mr Artist', '2007-04-29', 'calhouncory', 'https://wallace-mueller.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (41, NULL, 'Police Band', NULL, 'lindabarnes', 'http://rivera.com/', 1, '2014-12-20');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (42, 'Elizabeth Robertson', 'May Artist', '1994-07-02', 'smelendez', 'http://navarro.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (43, 'Peter Gonzalez', 'Spring Artist', '1977-03-28', 'linda24', 'https://www.johnson.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (44, 'Mark Smith', 'Rock Artist', '1979-01-09', 'brian45', 'http://www.walsh-mccarthy.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (45, NULL, 'Age Band', NULL, 'trujillodaniel', 'https://frederick.info/', 1, '2023-06-09');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (46, NULL, 'Challenge Band', NULL, 'charlesturner', 'https://stewart.com/', 1, '1999-08-03');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (47, NULL, 'Include Band', NULL, 'colton80', 'https://cox.com/', 1, '2013-09-30');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (48, 'Jennifer Buchanan', 'It Artist', '1979-03-05', 'grantjacob', 'https://snyder.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (49, NULL, 'Live Band', NULL, 'thompsonalexis', 'http://www.johnson.biz/', 1, '2008-02-29');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (50, 'Stacy Perkins', 'Very Artist', '1997-11-01', 'edgarbrown', 'http://sandoval.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (51, NULL, 'Position Band', NULL, 'emily56', 'https://www.thornton-shields.com/', 1, '2011-08-22');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (52, NULL, 'Hard Band', NULL, 'angeladavis', 'https://baker.com/', 1, '2010-12-25');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (53, 'Marissa Daniels', 'Hold Artist', '1985-08-14', 'kendra20', 'http://johnson.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (54, NULL, 'Third Band', NULL, 'michaelrobertson', 'http://vasquez.com/', 1, '2019-02-24');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (55, NULL, 'Place Band', NULL, 'susansmith', 'https://parks.org/', 1, '2006-09-20');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (56, NULL, 'Win Band', NULL, 'amandawebb', 'https://www.collins.com/', 1, '2014-06-22');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (57, 'Michael Wilson', 'Avoid Artist', '1985-11-28', 'garrettcandace', 'https://stark.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (58, 'Andrew Norton', 'Traditional Artist', '1971-01-06', 'jeanettesmith', 'http://www.rivera.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (59, NULL, 'Onto Band', NULL, 'brandonjohnson', 'http://oconnor.com/', 1, '2023-08-15');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (60, NULL, 'Table Band', NULL, 'pscott', 'http://scott-johnston.net/', 1, '2011-01-19');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (61, NULL, 'Item Band', NULL, 'tyler32', 'http://www.harris-nolan.com/', 1, '2002-01-28');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (62, 'Michael Rivers', 'Spend Artist', '2003-02-11', 'hlee', 'http://simmons.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (63, NULL, 'Leg Band', NULL, 'richard33', 'https://www.cooper.com/', 1, '1998-01-17');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (64, NULL, 'Energy Band', NULL, 'brianna36', 'https://www.buck.com/', 1, '2002-07-26');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (65, 'Deanna Strickland', 'Term Artist', '1967-10-07', 'stephaniewalker', 'http://weaver.org/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (66, 'Carl Moreno', 'Civil Artist', '1971-01-25', 'paynetravis', 'http://williams-frost.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (67, 'Richard Berger', 'Ten Artist', '1975-10-06', 'fernandezshannon', 'https://www.anderson-becker.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (68, NULL, 'Factor Band', NULL, 'briggsdwayne', 'http://www.shaffer.com/', 1, '2016-03-22');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (69, NULL, 'Maintain Band', NULL, 'rlevine', 'https://www.phillips-thomas.com/', 1, '1998-10-08');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (70, 'Kristen Jenkins', 'Fast Artist', '1965-07-08', 'gary03', 'https://www.herrera.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (71, 'Thomas Smith', 'Personal Artist', '1981-12-04', 'savagechase', 'http://page-brown.info/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (72, NULL, 'Lawyer Band', NULL, 'tanya26', 'https://williams-warren.com/', 1, '2015-05-23');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (73, 'Jeffery Harris', 'Important Artist', '2007-03-04', 'areynolds', 'http://www.elliott.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (74, 'Joel Hernandez', 'During Artist', '1992-12-02', 'dianaroberts', 'http://www.scott.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (75, 'Susan Branch', 'Live Artist', '1983-09-25', 'jimenezdonna', 'http://www.klein.com/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (76, NULL, 'Energy Band', NULL, 'hendricksdaniel', 'http://smith.org/', 1, '2011-11-03');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (77, NULL, 'Rest Band', NULL, 'anthonyhoward', 'http://www.johnston.org/', 1, '1997-09-23');
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (78, 'Caleb Howard', 'Market Artist', '2005-10-05', 'beverlymartin', 'https://www.sparks-ibarra.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (79, 'Barbara Rose', 'Rise Artist', '1967-01-22', 'darrellrussell', 'http://www.riley-bell.net/', 0, NULL);
INSERT INTO Performer (ID, Real_Name, Stage_Name, Birthday, Instagram, Website, Is_Band, Formation_Date) VALUES (80, NULL, 'State Band', NULL, 'mgonzalez', 'https://rodriguez.com/', 1, '2006-09-28');

-- Generated INSERTs for Membership table
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (69, 2, '2023-05-13');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (29, 3, '2019-06-28');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (27, 4, '2024-04-17');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (37, 11, '2021-02-28');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (54, 17, '2018-07-20');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (45, 19, '2022-03-21');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (45, 20, '2019-07-25');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (25, 21, '2022-06-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (56, 26, '2024-07-15');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (45, 36, '2018-05-17');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (35, 40, '2022-08-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (55, 48, '2015-05-22');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (63, 53, '2017-06-26');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (39, 65, '2018-12-05');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (41, 71, '2023-06-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (35, 73, '2019-02-20');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (60, 74, '2017-11-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (56, 79, '2022-05-06');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (1, 2, '2023-03-25');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (6, 3, '2016-09-16');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (7, 4, '2024-07-30');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (8, 5, '2021-08-22');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (9, 11, '2023-02-18');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (10, 12, '2022-07-29');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (14, 13, '2018-07-06');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (18, 15, '2018-12-01');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (23, 16, '2021-08-29');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (24, 17, '2016-05-04');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (25, 19, '2018-03-29');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (27, 20, '2016-01-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (29, 21, '2021-03-04');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (31, 22, '2018-08-12');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (33, 26, '2019-05-15');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (37, 28, '2022-07-04');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (39, 30, '2024-02-09');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (41, 32, '2024-05-12');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (46, 34, '2021-11-08');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (47, 36, '2025-05-02');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (49, 38, '2024-06-01');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (51, 40, '2017-05-10');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (52, 42, '2024-08-16');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (54, 43, '2018-06-12');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (55, 44, '2022-01-10');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (59, 48, '2019-07-10');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (60, 50, '2018-03-07');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (61, 53, '2022-09-15');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (63, 57, '2018-02-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (64, 58, '2016-06-30');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (68, 62, '2016-07-14');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (69, 65, '2018-11-08');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (72, 66, '2024-12-05');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (76, 67, '2024-07-26');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (77, 70, '2018-03-06');
INSERT INTO Membership (Band_ID, Artist_ID, Join_Date) VALUES (80, 71, '2021-01-05');
