-- Generated INSERTs for Stage table (50 rows)
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (1, 'Carroll Inc Stage', 'Brother set line here decide.', 117, 'Pre-emptive 4thgeneration info-mediaries');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (2, 'Lawson-Wang Stage', 'Entire soon option bill fish against power.', 172, 'Advanced homogeneous software');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (3, 'Costa Ltd Stage', 'Month shake voice.', 197, 'Reactive discrete hardware');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (4, 'Rhodes Group Stage', 'Unit indicate trouble two beyond.', 108, 'Self-enabling uniform frame');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (5, 'Paul Ltd Stage', 'View instead stop prove field onto think.', 132, 'Profit-focused hybrid parallelism');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (6, 'Castillo Ltd Stage', 'Increase common nature reflect purpose hear.', 115, 'Organic stable migration');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (7, 'Osborne PLC Stage', 'Have run light final summer pass.', 163, 'Reduced hybrid project');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (8, 'Jackson and Sons Stage', 'Side much team.', 197, 'Focused impactful migration');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (9, 'Farley-Lane Stage', 'Travel process participant role himself tax west.', 157, 'User-centric multimedia workforce');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (10, 'Stone PLC Stage', 'International argue thank now customer.', 160, 'Profit-focused incremental matrix');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (11, 'Perry-Smith Stage', 'Perhaps partner leader agreement director concern once.', 183, 'Cross-group neutral website');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (12, 'Johnson-Acevedo Stage', 'Bar admit address sense.', 148, 'Fully-configurable encompassing budgetary management');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (13, 'Lopez, Roberts and Jackson Stage', 'Month collection evening represent lawyer.', 200, 'Inverse modular leverage');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (14, 'Johnson Group Stage', 'Inside could board tonight member decide.', 126, 'Robust intermediate adapter');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (15, 'Smith and Sons Stage', 'Responsibility civil relate.', 112, 'Synergistic interactive moratorium');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (16, 'Rowland Ltd Stage', 'Late model air push sound process international.', 162, 'User-centric exuding capacity');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (17, 'Hutchinson LLC Stage', 'Teach financial vote season.', 103, 'Operative non-volatile extranet');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (18, 'Smith Inc Stage', 'Standard while now commercial test wind region meeting.', 149, 'Multi-tiered dedicated hardware');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (19, 'Harris Ltd Stage', 'Option manage visit hope mean admit.', 155, 'Seamless impactful forecast');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (20, 'Moore LLC Stage', 'Situation fund defense purpose study usually gas.', 177, 'Synergized national matrix');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (21, 'Young, Swanson and Miller Stage', 'Coach Mrs environmental forward.', 197, 'Profit-focused eco-centric hub');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (22, 'Peterson-Carter Stage', 'Single resource major oil show fly image herself.', 198, 'Digitized clear-thinking Graphical User Interface');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (23, 'Gilbert Group Stage', 'Number difference bank entire.', 100, 'Implemented non-volatile monitoring');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (24, 'Ellis LLC Stage', 'Skin still actually prove.', 189, 'Cross-group incremental budgetary management');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (25, 'Lopez PLC Stage', 'Class late race city suddenly itself.', 157, 'Multi-tiered needs-based frame');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (26, 'King, Woods and Garcia Stage', 'Always action work far others last.', 134, 'Intuitive impactful architecture');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (27, 'Gentry PLC Stage', 'Born Democrat pay woman myself read product.', 192, 'Fundamental contextually-based moratorium');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (28, 'Parker and Sons Stage', 'Bank exactly work language present poor.', 129, 'Focused human-resource function');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (29, 'Murphy LLC Stage', 'Throw field free name often other each after.', 175, 'Fully-configurable impactful archive');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (30, 'Arnold-Jones Stage', 'Again act seek grow.', 113, 'Phased coherent attitude');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (31, 'Strickland, Murphy and Hicks Stage', 'Conference change center tend.', 140, 'Integrated bi-directional strategy');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (32, 'Davenport, Guzman and Martinez Stage', 'Center treat all firm total.', 103, 'Synergistic neutral synergy');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (33, 'Harris, Evans and Medina Stage', 'Resource property education.', 102, 'Cloned systemic knowledge user');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (34, 'Dunn-Weaver Stage', 'Law how full election agency position indicate.', 103, 'Re-engineered 3rdgeneration approach');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (35, 'Kelly, Taylor and Martinez Stage', 'Work everybody nor common become.', 183, 'Pre-emptive 24hour conglomeration');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (36, 'Stewart, Orozco and Knapp Stage', 'Draw manager long different include.', 169, 'Realigned reciprocal superstructure');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (37, 'Hill, Lucas and Williams Stage', 'Shake population happy memory.', 101, 'Expanded fault-tolerant framework');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (38, 'Evans, Tran and Martin Stage', 'Organization task to whether number computer economy.', 148, 'Extended non-volatile success');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (39, 'Simpson Group Stage', 'Himself suddenly name yes model bed.', 187, 'Function-based responsive attitude');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (40, 'Doyle-Miller Stage', 'Wide pay whom rather.', 127, 'Configurable leadingedge encoding');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (41, 'Case-Berger Stage', 'Clearly for call training where budget.', 154, 'Right-sized national installation');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (42, 'Guerrero LLC Stage', 'Her nice where more often.', 192, 'Assimilated responsive portal');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (43, 'Conley and Sons Stage', 'Expect my event one.', 103, 'Function-based systemic knowledge user');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (44, 'Gardner Group Stage', 'Talk shoulder now himself exist board.', 167, 'Assimilated bottom-line open system');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (45, 'Smith, Phillips and Craig Stage', 'Away health south join.', 128, 'Synergistic heuristic task-force');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (46, 'Morris, Martinez and Robbins Stage', 'Fight human situation raise manage positive.', 197, 'Multi-tiered homogeneous database');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (47, 'Smith, Ramirez and George Stage', 'Current type over might visit Republican would.', 156, 'Total composite knowledge user');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (48, 'Barnett, Gonzalez and Fox Stage', 'Often wife from perform window record.', 163, 'User-friendly asymmetric methodology');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (49, 'Wright, Rasmussen and Carter Stage', 'Imagine picture plant.', 170, 'Object-based zero tolerance flexibility');
INSERT INTO Stage (ID, Name, Description, Capacity, Tech_Info) VALUES (50, 'Saunders PLC Stage', 'Glass enough remain.', 129, 'Synergized needs-based framework');
